version: '3'
services:
  mongodb-test:
    image: mongo:3.6.8
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: converto-test
    volumes:
      - mongodb_data:/data/db-test

volumes:
  mongodb_data:
